In [1]:
pip install shazamio sounddevice scipy

Collecting shazamioNote: you may need to restart the kernel to use updated packages.

  Downloading shazamio-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting sounddevice
  Downloading sounddevice-0.5.5-py3-none-win_amd64.whl.metadata (1.4 kB)
Requirement already satisfied: scipy in c:\users\amrit\downloads\anaconda\lib\site-packages (1.13.1)
Collecting aiofiles<24.0.0,>=23.2.1 (from shazamio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (3.10.5)
Collecting aiohttp-retry<3.0.0,>=2.8.3 (from shazamio)
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Collecting anyio<5.0.0,>=4.3.0 (from shazamio)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting dataclass-factory<3.0,>=2.16 (from shazamio)
  Downloading dataclass_factory-2.16-py3-none-any.whl.metadata (2.8 kB)
Collecting numpy<3.0.0,>=2.2.2 (from shazamio)
  Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting pydantic<3.0.0,>=2.9.2 (from shazamio)
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting pydub<0.26.0,>=0.25.1 (from shazamio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting shazamio-core==1.1.2 (from shazamio)
  Downloading shazamio_core-1.1.2-cp312-cp312-win_amd64.whl.metadata (369 bytes)
Requirement already satisfied: cffi in c:\users\amrit\downloads\anaconda\lib\site-packages (from sounddevice) (1.17.1)
Collecting numpy<3.0.0,>=2.2.2 (from shazamio)
  Downloading numpy-2.2.6-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.11.0)
Requirement already satisfied: idna>=2.8 in c:\users\amrit\downloads\anaconda\lib\site-packages (from anyio<5.0.0,>=4.3.0->shazamio) (3.7)
Requirement already satisfied: typing_extensions>=4.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from anyio<5.0.0,>=4.3.0->shazamio) (4.14.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic<3.0.0,>=2.9.2->shazamio) (0.6.0)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.9.2->shazamio)
  Downloading pydantic_core-2.46.4-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Collecting typing_extensions>=4.5 (from anyio<5.0.0,>=4.3.0->shazamio)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.9.2->shazamio)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: pycparser in c:\users\amrit\downloads\anaconda\lib\site-packages (from cffi->sounddevice) (2.21)
Downloading shazamio-0.8.1-py3-none-any.whl (36 kB)
Downloading shazamio_core-1.1.2-cp312-cp312-win_amd64.whl (817 kB)
   ---------------------------------------- 0.0/817.8 kB ? eta -:--:--
   ---------------------------------------- 817.8/817.8 kB 6.0 MB/s eta 0:00:00
Downloading sounddevice-0.5.5-py3-none-win_amd64.whl (365 kB)
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading aiohttp_retry-2.9.1-py3-none-any.whl (10.0 kB)
Downloading anyio-4.13.0-py3-none-any.whl (114 kB)
Downloading dataclass_factory-2.16-py3-none-any.whl (29 kB)
Downloading numpy-2.2.6-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------ --------------------------------- 2.1/12.6 MB 10.7 MB/s eta 0:00:01
   ------------- -------------------------- 4.2/12.6 MB 10.5 MB/s eta 0:00:01
   ---------------- ----------------------- 5.2/12.6 MB 8.4 MB/s eta 0:00:01
   ------------------- -------------------- 6.3/12.6 MB 7.7 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.6 MB 6.8 MB/s eta 0:00:01
   ------------------------ --------------- 7.9/12.6 MB 6.2 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 5.8 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 5.1 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 5.1 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 5.1 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 3.9 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.6 MB 3.4 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.6 MB 3.4 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.6 MB 3.1 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.6 MB 2.9 MB/s eta 0:00:02
   ------------------------------ --------- 9.7/12.6 MB 2.8 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.6 MB 2.7 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 2.7 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 2.6 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 2.6 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 2.4 MB/s eta 0:00:00
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.4-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.1 MB ? eta -:--:--
   --------------- ------------------------ 0.8/2.1 MB 2.1 MB/s eta 0:00:01
   ------------------------- -------------- 1.3/2.1 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 1.8/2.1 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 2.2 MB/s eta 0:00:00
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: pydub, typing_extensions, shazamio-core, numpy, dataclass-factory, aiofiles, typing-inspection, sounddevice, pydantic-core, anyio, pydantic, aiohttp-retry, shazamio
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.14.0
    Uninstalling typing_extensions-4.14.0:
      Successfully uninstalled typing_extensions-4.14.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: pydantic-core
    Found existing installation: pydantic_core 2.20.1
    Uninstalling pydantic_core-2.20.1:
      Successfully uninstalled pydantic_core-2.20.1
  Attempting uninstall: anyio
    Found existing installation: anyio 4.2.0
    Uninstalling anyio-4.2.0:
      Successfully uninstalled anyio-4.2.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.8.2
    Uninstalling pydantic-2.8.2:
      Successfully uninstalled pydantic-2.8.2
Successfully installed aiofiles-23.2.1 aiohttp-retry-2.9.1 anyio-4.13.0 dataclass-factory-2.16 numpy-2.2.6 pydantic-2.13.4 pydantic-core-2.46.4 pydub-0.25.1 shazamio-0.8.1 shazamio-core-1.1.2 sounddevice-0.5.5 typing-inspection-0.4.2 typing_extensions-4.15.0

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.2.6 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.2.6 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.6 which is incompatible.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.2 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.
streamlit 1.37.1 requires rich<14,>=10.14.0, but you have rich 15.0.0 which is incompatible.
ydata-profiling 4.16.1 requires numpy<2.2,>=1.16.0, but you have numpy 2.2.6 which is incompatible.

In [2]:
import sounddevice as sd
from scipy.io.wavfile import write

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\amrit\Downloads\anaconda\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\amrit\Downloads\anaconda\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\amrit\Downloads\anaconda\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\Users\amrit\Downloads\anaconda\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\amrit\AppData\Local\Temp\ipykernel_30800\3767535527.py", line 2, in <module>
    from scipy.io.wavfile import write
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\scipy\io\__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\scipy\io\matlab\__init__.py", line 45, in <module>
    from ._mio import loadmat, savemat, whosmat
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\scipy\io\matlab\_mio.py", line 9, in <module>
    from ._mio4 import MatFile4Reader, MatFile4Writer
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\scipy\io\matlab\_mio4.py", line 8, in <module>
    import scipy.sparse
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\scipy\sparse\__init__.py", line 295, in <module>
    from ._csr import *
  File "C:\Users\amrit\Downloads\anaconda\Lib\site-packages\scipy\sparse\_csr.py", line 11, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

In [4]:
import numpy as np

print(np.__version__)

2.2.6

In [6]:
!pip uninstall numpy -y

!pip install numpy==1.26.4

Found existing installation: numpy 2.2.6
Uninstalling numpy-2.2.6:
  Successfully uninstalled numpy-2.2.6

WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~umpy.libs'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~-mpy'.
You can safely remove it manually.

Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   --- ------------------------------------ 1.3/15.5 MB 8.4 MB/s eta 0:00:02
   ------------ --------------------------- 4.7/15.5 MB 14.2 MB/s eta 0:00:01
   -------------- ------------------------- 5.5/15.5 MB 10.2 MB/s eta 0:00:01
   ---------------- ----------------------- 6.3/15.5 MB 8.2 MB/s eta 0:00:02
   ---------------- ----------------------- 6.3/15.5 MB 8.2 MB/s eta 0:00:02
   ---------------- ----------------------- 6.3/15.5 MB 8.2 MB/s eta 0:00:02
   ---------------- ----------------------- 6.6/15.5 MB 4.6 MB/s eta 0:00:02
   -------------------- ------------------- 7.9/15.5 MB 4.6 MB/s eta 0:00:02
   ---------------------- ----------------- 8.9/15.5 MB 4.7 MB/s eta 0:00:02
   ------------------------- -------------- 10.0/15.5 MB 4.7 MB/s eta 0:00:02
   ----------------------------- ---------- 11.3/15.5 MB 4.8 MB/s eta 0:00:01
   ------------------------------- -------- 12.3/15.5 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 13.1/15.5 MB 4.8 MB/s eta 0:00:01
   ----------------------------------- ---- 13.9/15.5 MB 4.6 MB/s eta 0:00:01
   ------------------------------------ --- 14.2/15.5 MB 4.5 MB/s eta 0:00:01
   ------------------------------------- -- 14.7/15.5 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 4.1 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.26.4

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.2 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.
shazamio 0.8.1 requires numpy<3.0.0,>=2.2.2, but you have numpy 1.26.4 which is incompatible.
streamlit 1.37.1 requires rich<14,>=10.14.0, but you have rich 15.0.0 which is incompatible.

In [7]:
!pip install --upgrade scipy sounddevice shazamio

Requirement already satisfied: scipy in c:\users\amrit\downloads\anaconda\lib\site-packages (1.13.1)
Collecting scipy
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: sounddevice in c:\users\amrit\downloads\anaconda\lib\site-packages (0.5.5)
Requirement already satisfied: shazamio in c:\users\amrit\downloads\anaconda\lib\site-packages (0.8.1)
Requirement already satisfied: numpy<2.7,>=1.26.4 in c:\users\amrit\downloads\anaconda\lib\site-packages (from scipy) (1.26.4)
Requirement already satisfied: cffi in c:\users\amrit\downloads\anaconda\lib\site-packages (from sounddevice) (1.17.1)
Requirement already satisfied: aiofiles<24.0.0,>=23.2.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (23.2.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (3.10.5)
Requirement already satisfied: aiohttp-retry<3.0.0,>=2.8.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (2.9.1)
Requirement already satisfied: anyio<5.0.0,>=4.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (4.13.0)
Requirement already satisfied: dataclass-factory<3.0,>=2.16 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (2.16)
Collecting numpy<2.7,>=1.26.4 (from scipy)
  Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.9.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (2.13.4)
Requirement already satisfied: pydub<0.26.0,>=0.25.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (0.25.1)
Requirement already satisfied: shazamio-core==1.1.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (1.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.11.0)
Requirement already satisfied: idna>=2.8 in c:\users\amrit\downloads\anaconda\lib\site-packages (from anyio<5.0.0,>=4.3.0->shazamio) (3.7)
Requirement already satisfied: typing_extensions>=4.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from anyio<5.0.0,>=4.3.0->shazamio) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic<3.0.0,>=2.9.2->shazamio) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic<3.0.0,>=2.9.2->shazamio) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic<3.0.0,>=2.9.2->shazamio) (0.4.2)
Requirement already satisfied: pycparser in c:\users\amrit\downloads\anaconda\lib\site-packages (from cffi->sounddevice) (2.21)
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   -- ------------------------------------- 1.8/36.5 MB 12.6 MB/s eta 0:00:03
   ----- ---------------------------------- 4.7/36.5 MB 15.9 MB/s eta 0:00:03
   ------ --------------------------------- 5.5/36.5 MB 10.5 MB/s eta 0:00:03
   ------ --------------------------------- 6.3/36.5 MB 8.4 MB/s eta 0:00:04
   ------- -------------------------------- 7.1/36.5 MB 7.4 MB/s eta 0:00:04
   -------- ------------------------------- 7.6/36.5 MB 6.6 MB/s eta 0:00:05
   --------- ------------------------------ 8.4/36.5 MB 6.0 MB/s eta 0:00:05
   ---------- ----------------------------- 9.2/36.5 MB 5.6 MB/s eta 0:00:05
   ---------- ----------------------------- 10.0/36.5 MB 5.3 MB/s eta 0:00:06
   ----------- ---------------------------- 10.5/36.5 MB 5.2 MB/s eta 0:00:06
   ------------ --------------------------- 11.3/36.5 MB 5.0 MB/s eta 0:00:06
   ------------- -------------------------- 12.1/36.5 MB 4.8 MB/s eta 0:00:06
   -------------- ------------------------- 12.8/36.5 MB 4.8 MB/s eta 0:00:05
   --------------- ------------------------ 13.9/36.5 MB 4.7 MB/s eta 0:00:05
   ---------------- ----------------------- 14.7/36.5 MB 4.6 MB/s eta 0:00:05
   ---------------- ----------------------- 15.2/36.5 MB 4.6 MB/s eta 0:00:05
   ----------------- ---------------------- 16.3/36.5 MB 4.5 MB/s eta 0:00:05
   ------------------ --------------------- 17.0/36.5 MB 4.5 MB/s eta 0:00:05
   ------------------- -------------------- 17.8/36.5 MB 4.4 MB/s eta 0:00:05
   -------------------- ------------------- 18.6/36.5 MB 4.4 MB/s eta 0:00:05
   -------------------- ------------------- 19.1/36.5 MB 4.3 MB/s eta 0:00:05
   --------------------- ------------------ 19.9/36.5 MB 4.3 MB/s eta 0:00:04
   ---------------------- ----------------- 20.7/36.5 MB 4.3 MB/s eta 0:00:04
   ----------------------- ---------------- 21.5/36.5 MB 4.2 MB/s eta 0:00:04
   ------------------------ --------------- 22.3/36.5 MB 4.2 MB/s eta 0:00:04
   ------------------------- -------------- 23.1/36.5 MB 4.2 MB/s eta 0:00:04
   -------------------------- ------------- 24.1/36.5 MB 4.2 MB/s eta 0:00:03
   -------------------------- ------------- 24.6/36.5 MB 4.1 MB/s eta 0:00:03
   --------------------------- ------------ 25.2/36.5 MB 4.1 MB/s eta 0:00:03
   ---------------------------- ----------- 25.7/36.5 MB 4.0 MB/s eta 0:00:03
   ---------------------------- ----------- 26.2/36.5 MB 4.0 MB/s eta 0:00:03
   ----------------------------- ---------- 26.7/36.5 MB 3.9 MB/s eta 0:00:03
   ----------------------------- ---------- 27.3/36.5 MB 3.9 MB/s eta 0:00:03
   ------------------------------ --------- 27.8/36.5 MB 3.8 MB/s eta 0:00:03
   ------------------------------ --------- 28.3/36.5 MB 3.8 MB/s eta 0:00:03
   ------------------------------- -------- 28.8/36.5 MB 3.8 MB/s eta 0:00:03
   -------------------------------- ------- 29.6/36.5 MB 3.7 MB/s eta 0:00:02
   -------------------------------- ------- 30.1/36.5 MB 3.7 MB/s eta 0:00:02
   --------------------------------- ------ 30.9/36.5 MB 3.7 MB/s eta 0:00:02
   ---------------------------------- ----- 31.5/36.5 MB 3.7 MB/s eta 0:00:02
   ----------------------------------- ---- 32.2/36.5 MB 3.7 MB/s eta 0:00:02
   ----------------------------------- ---- 32.8/36.5 MB 3.7 MB/s eta 0:00:02
   ------------------------------------ --- 33.6/36.5 MB 3.7 MB/s eta 0:00:01
   ------------------------------------- -- 34.3/36.5 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.5 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.5 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 3.6 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 3.7 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/12.3 MB 4.0 MB/s eta 0:00:03
   ------- -------------------------------- 2.4/12.3 MB 3.9 MB/s eta 0:00:03
   ----------- ---------------------------- 3.4/12.3 MB 4.1 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.3 MB 4.1 MB/s eta 0:00:03
   ----------------- ---------------------- 5.2/12.3 MB 4.2 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.3 MB 4.2 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.3 MB 4.2 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.3 MB 4.3 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 4.3 MB/s eta 0:00:01
   --------------------------------- ------ 10.2/12.3 MB 4.4 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 4.4 MB/s eta 0:00:00
Installing collected packages: numpy, scipy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: scipy
    Found existing installation: scipy 1.13.1
    Uninstalling scipy-1.13.1:
      Successfully uninstalled scipy-1.13.1
Successfully installed numpy-2.4.6 scipy-1.17.1

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~cipy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.6 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.4.6 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.17.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.6 which is incompatible.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.2 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.
streamlit 1.37.1 requires rich<14,>=10.14.0, but you have rich 15.0.0 which is incompatible.
ydata-profiling 4.16.1 requires numpy<2.2,>=1.16.0, but you have numpy 2.4.6 which is incompatible.
ydata-profiling 4.16.1 requires scipy<1.16,>=1.4.1, but you have scipy 1.17.1 which is incompatible.

In [1]:
import numpy as np
import scipy
import sounddevice

print("NumPy:", np.__version__)
print("SciPy OK")
print("SoundDevice OK")

NumPy: 2.4.6
SciPy OK
SoundDevice OK

In [2]:
import sys
print(sys.executable)

C:\Users\amrit\Downloads\anaconda\python.exe

In [3]:
import numpy as np
print(np.__version__)
print(np.__file__)

2.4.6
C:\Users\amrit\Downloads\anaconda\Lib\site-packages\numpy\__init__.py

In [4]:
!where python

C:\Users\amrit\Downloads\anaconda\python.exe
C:\Program Files\Python313\python.exe
C:\Users\amrit\AppData\Local\Microsoft\WindowsApps\python.exe

In [5]:
!pip show numpy

Name: numpy
Version: 2.4.6
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License:
Location: C:\Users\amrit\Downloads\anaconda\Lib\site-packages
Requires:
Required-by: altair, astropy, bokeh, Bottleneck, catboost, contourpy, datashader, gensim, h5py, holoviews, hvplot, imagecodecs, ImageHash, imageio, imbalanced-learn, matplotlib, missingno, mkl_fft, mkl_random, numba, numexpr, pandas, pandas-profiling, patsy, phik, pyarrow, pydeck, pyerfa, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, sentence-transformers, shazamio, statsmodels, streamlit, tables, tifffile, transformers, visions, wordcloud, xarray, ydata-profiling

In [6]:
import sys

!{sys.executable} -m pip uninstall numpy -y
!{sys.executable} -m pip install numpy==1.26.4

Found existing installation: numpy 2.4.6
Uninstalling numpy-2.4.6:
  Successfully uninstalled numpy-2.4.6

WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~-mpy.libs'.
You can safely remove it manually.
WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~~mpy'.
You can safely remove it manually.

Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Using cached numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
Installing collected packages: numpy
Successfully installed numpy-1.26.4

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.17.1 which is incompatible.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.2 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.
shazamio 0.8.1 requires numpy<3.0.0,>=2.2.2, but you have numpy 1.26.4 which is incompatible.
streamlit 1.37.1 requires rich<14,>=10.14.0, but you have rich 15.0.0 which is incompatible.
ydata-profiling 4.16.1 requires scipy<1.16,>=1.4.1, but you have scipy 1.17.1 which is incompatible.

In [1]:
import numpy as np
print(np.__version__)

1.26.4

In [2]:
import sys
print(sys.executable)

C:\Users\amrit\Downloads\anaconda\python.exe

In [3]:
!pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

----

The NumPy repository and source distributions bundle several libraries that are
compatibly licensed.  We list these here.

Name: lapack-lite
Files: numpy/linalg/lapack_lite/*
License: BSD-3-Clause
  For details, see numpy/linalg/lapack_lite/LICENSE.txt

Name: tempita
Files: tools/npy_tempita/*
License: MIT
  For details, see tools/npy_tempita/license.txt

Name: dragon4
Files: numpy/core/src/multiarray/dragon4.c
License: MIT
  For license text, see numpy/core/src/multiarray/dragon4.c

Name: libdivide
Files: numpy/core/include/numpy/libdivide/*
License: Zlib
  For license text, see numpy/core/include/numpy/libdivide/LICENSE.txt


Note that the following files are vendored in the repository and sdist but not
installed in built numpy packages:

Name: Meson
Files: vendored-meson/meson/*
License: Apache 2.0
  For license text, see vendored-meson/meson/COPYING

Name: spin
Files: .spin/cmds.py
License: BSD-3
  For license text, see .spin/LICENSE

----

This binary distribution of NumPy also bundles the following software:


Name: OpenBLAS
Files: numpy.libs\libopenblas*.dll
Description: bundled as a dynamically linked library
Availability: https://github.com/OpenMathLib/OpenBLAS/
License: BSD-3-Clause
  Copyright (c) 2011-2014, The OpenBLAS Project
  All rights reserved.

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

     1. Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.

     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in
        the documentation and/or other materials provided with the
        distribution.
     3. Neither the name of the OpenBLAS project nor the names of
        its contributors may be used to endorse or promote products
        derived from this software without specific prior written
        permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


Name: LAPACK
Files: numpy.libs\libopenblas*.dll
Description: bundled in OpenBLAS
Availability: https://github.com/OpenMathLib/OpenBLAS/
License: BSD-3-Clause-Attribution
  Copyright (c) 1992-2013 The University of Tennessee and The University
                          of Tennessee Research Foundation.  All rights
                          reserved.
  Copyright (c) 2000-2013 The University of California Berkeley. All
                          rights reserved.
  Copyright (c) 2006-2013 The University of Colorado Denver.  All rights
                          reserved.

  $COPYRIGHT$

  Additional copyrights may follow

  $HEADER$

  Redistribution and use in source and binary forms, with or without
  modification, are permitted provided that the following conditions are
  met:

  - Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

  - Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer listed
    in this license in the documentation and/or other materials
    provided with the distribution.

  - Neither the name of the copyright holders nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.

  The copyright holders provide no reassurances that the source code
  provided does not infringe any patent, copyright, or any other
  intellectual property rights of third parties.  The copyright holders
  disclaim any liability to any recipient for claims brought against
  recipient by any third party for infringement of that parties
  intellectual property rights.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


Name: GCC runtime library
Files: numpy.libs\libopenblas*.dll
Description: statically linked to files compiled with gcc
Availability: https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=libgfortran
License: GPL-3.0-with-GCC-exception
  Copyright (C) 2002-2017 Free Software Foundation, Inc.

  Libgfortran is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3, or (at your option)
  any later version.

  Libgfortran is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  Under Section 7 of GPL version 3, you are granted additional
  permissions described in the GCC Runtime Library Exception, version
  3.1, as published by the Free Software Foundation.

  You should have received a copy of the GNU General Public License and
  a copy of the GCC Runtime Library Exception along with this program;
  see the files COPYING3 and COPYING.RUNTIME respectively.  If not, see
  <http://www.gnu.org/licenses/>.

----

Full text of license texts referred to above follows (that they are
listed below does not necessarily imply the conditions apply to the
present binary release):

----

GCC RUNTIME LIBRARY EXCEPTION

Version 3.1, 31 March 2009

Copyright (C) 2009 Free Software Foundation, Inc. <http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.

This GCC Runtime Library Exception ("Exception") is an additional
permission under section 7 of the GNU General Public License, version
3 ("GPLv3"). It applies to a given file (the "Runtime Library") that
bears a notice placed by the copyright holder of the file stating that
the file is governed by GPLv3 along with this Exception.

When you use GCC to compile a program, GCC may combine portions of
certain GCC header files and runtime libraries with the compiled
program. The purpose of this Exception is to allow compilation of
non-GPL (including proprietary) programs to use, in this way, the
header files and runtime libraries covered by this Exception.

0. Definitions.

A file is an "Independent Module" if it either requires the Runtime
Library for execution after a Compilation Process, or makes use of an
interface provided by the Runtime Library, but is not otherwise based
on the Runtime Library.

"GCC" means a version of the GNU Compiler Collection, with or without
modifications, governed by version 3 (or a specified later version) of
the GNU General Public License (GPL) with the option of using any
subsequent versions published by the FSF.

"GPL-compatible Software" is software whose conditions of propagation,
modification and use would permit combination with GCC in accord with
the license of GCC.

"Target Code" refers to output from any compiler for a real or virtual
target processor architecture, in executable form or suitable for
input to an assembler, loader, linker and/or execution
phase. Notwithstanding that, Target Code does not include data in any
format that is used as a compiler intermediate representation, or used
for producing a compiler intermediate representation.

The "Compilation Process" transforms code entirely represented in
non-intermediate languages designed for human-written code, and/or in
Java Virtual Machine byte code, into Target Code. Thus, for example,
use of source code generators and preprocessors need not be considered
part of the Compilation Process, since the Compilation Process can be
understood as starting with the output of the generators or
preprocessors.

A Compilation Process is "Eligible" if it is done using GCC, alone or
with other GPL-compatible software, or if it is done without using any
work based on GCC. For example, using non-GPL-compatible Software to
optimize any GCC intermediate representations would not qualify as an
Eligible Compilation Process.

1. Grant of Additional Permission.

You have permission to propagate a work of Target Code formed by
combining the Runtime Library with Independent Modules, even if such
propagation would otherwise violate the terms of GPLv3, provided that
all Target Code was generated by Eligible Compilation Processes. You
may then convey such a combination under terms of your choice,
consistent with the licensing of the Independent Modules.

2. No Weakening of GCC Copyleft.

The availability of this Exception does not imply any general
presumption that third-party software is unaffected by the copyleft
requirements of the license of GCC.

----

                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

                            Preamble

  The GNU General Public License is a free, copyleft license for
software and other kinds of works.

  The licenses for most software and other practical works are designed
to take away your freedom to share and change the works.  By contrast,
the GNU General Public License is intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.  We, the Free Software Foundation, use the
GNU General Public License for most of our software; it applies also to
any other work released this way by its authors.  You can apply it to
your programs, too.

  When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.

  To protect your rights, we need to prevent others from denying you
these rights or asking you to surrender the rights.  Therefore, you have
certain responsibilities if you distribute copies of the software, or if
you modify it: responsibilities to respect the freedom of others.

  For example, if you distribute copies of such a program, whether
gratis or for a fee, you must pass on to the recipients the same
freedoms that you received.  You must make sure that they, too, receive
or can get the source code.  And you must show them these terms so they
know their rights.

  Developers that use the GNU GPL protect your rights with two steps:
(1) assert copyright on the software, and (2) offer you this License
giving you legal permission to copy, distribute and/or modify it.

  For the developers' and authors' protection, the GPL clearly explains
that there is no warranty for this free software.  For both users' and
authors' sake, the GPL requires that modified versions be marked as
changed, so that their problems will not be attributed erroneously to
authors of previous versions.

  Some devices are designed to deny users access to install or run
modified versions of the software inside them, although the manufacturer
can do so.  This is fundamentally incompatible with the aim of
protecting users' freedom to change the software.  The systematic
pattern of such abuse occurs in the area of products for individuals to
use, which is precisely where it is most unacceptable.  Therefore, we
have designed this version of the GPL to prohibit the practice for those
products.  If such problems arise substantially in other domains, we
stand ready to extend this provision to those domains in future versions
of the GPL, as needed to protect the freedom of users.

  Finally, every program is threatened constantly by software patents.
States should not allow patents to restrict development and use of
software on general-purpose computers, but in those that do, we wish to
avoid the special danger that patents applied to a free program could
make it effectively proprietary.  To prevent this, the GPL assures that
patents cannot be used to render the program non-free.

  The precise terms and conditions for copying, distribution and
modification follow.

                       TERMS AND CONDITIONS

  0. Definitions.

  "This License" refers to version 3 of the GNU General Public License.

  "Copyright" also means copyright-like laws that apply to other kinds of
works, such as semiconductor masks.

  "The Program" refers to any copyrightable work licensed under this
License.  Each licensee is addressed as "you".  "Licensees" and
"recipients" may be individuals or organizations.

  To "modify" a work means to copy from or adapt all or part of the work
in a fashion requiring copyright permission, other than the making of an
exact copy.  The resulting work is called a "modified version" of the
earlier work or a work "based on" the earlier work.

  A "covered work" means either the unmodified Program or a work based
on the Program.

  To "propagate" a work means to do anything with it that, without
permission, would make you directly or secondarily liable for
infringement under applicable copyright law, except executing it on a
computer or modifying a private copy.  Propagation includes copying,
distribution (with or without modification), making available to the
public, and in some countries other activities as well.

  To "convey" a work means any kind of propagation that enables other
parties to make or receive copies.  Mere interaction with a user through
a computer network, with no transfer of a copy, is not conveying.

  An interactive user interface displays "Appropriate Legal Notices"
to the extent that it includes a convenient and prominently visible
feature that (1) displays an appropriate copyright notice, and (2)
tells the user that there is no warranty for the work (except to the
extent that warranties are provided), that licensees may convey the
work under this License, and how to view a copy of this License.  If
the interface presents a list of user commands or options, such as a
menu, a prominent item in the list meets this criterion.

  1. Source Code.

  The "source code" for a work means the preferred form of the work
for making modifications to it.  "Object code" means any non-source
form of a work.

  A "Standard Interface" means an interface that either is an official
standard defined by a recognized standards body, or, in the case of
interfaces specified for a particular programming language, one that
is widely used among developers working in that language.

  The "System Libraries" of an executable work include anything, other
than the work as a whole, that (a) is included in the normal form of
packaging a Major Component, but which is not part of that Major
Component, and (b) serves only to enable use of the work with that
Major Component, or to implement a Standard Interface for which an
implementation is available to the public in source code form.  A
"Major Component", in this context, means a major essential component
(kernel, window system, and so on) of the specific operating system
(if any) on which the executable work runs, or a compiler used to
produce the work, or an object code interpreter used to run it.

  The "Corresponding Source" for a work in object code form means all
the source code needed to generate, install, and (for an executable
work) run the object code and to modify the work, including scripts to
control those activities.  However, it does not include the work's
System Libraries, or general-purpose tools or generally available free
programs which are used unmodified in performing those activities but
which are not part of the work.  For example, Corresponding Source
includes interface definition files associated with source files for
the work, and the source code for shared libraries and dynamically
linked subprograms that the work is specifically designed to require,
such as by intimate data communication or control flow between those
subprograms and other parts of the work.

  The Corresponding Source need not include anything that users
can regenerate automatically from other parts of the Corresponding
Source.

  The Corresponding Source for a work in source code form is that
same work.

  2. Basic Permissions.

  All rights granted under this License are granted for the term of
copyright on the Program, and are irrevocable provided the stated
conditions are met.  This License explicitly affirms your unlimited
permission to run the unmodified Program.  The output from running a
covered work is covered by this License only if the output, given its
content, constitutes a covered work.  This License acknowledges your
rights of fair use or other equivalent, as provided by copyright law.


In [4]:
import sounddevice as sd

print(sd.query_devices())

   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
>  1 Microphone Array (AMD Audio Dev, MME (2 in, 0 out)
   2 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  3 Speakers (Realtek(R) Audio), MME (0 in, 2 out)
   4 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
   5 Microphone Array (AMD Audio Device), Windows DirectSound (2 in, 0 out)
   6 Primary Sound Driver, Windows DirectSound (0 in, 2 out)
   7 Speakers (Realtek(R) Audio), Windows DirectSound (0 in, 2 out)
   8 Speakers (Realtek(R) Audio), Windows WASAPI (0 in, 2 out)
   9 Microphone Array (AMD Audio Device), Windows WASAPI (2 in, 0 out)
  10 Speakers 1 (Realtek HD Audio output with HAP), Windows WDM-KS (0 in, 2 out)
  11 Speakers 2 (Realtek HD Audio output with HAP), Windows WDM-KS (0 in, 2 out)
  12 PC Speaker (Realtek HD Audio output with HAP), Windows WDM-KS (2 in, 0 out)
  13 Stereo Mix (Realtek HD Audio Stereo input), Windows WDM-KS (2 in, 0 out)
  14 Microphone (Realtek HD Audio Mic input), Windows WDM-KS (2 in, 0 out)
  15 Headphones 1 (Realtek HD Audio 2nd output with HAP), Windows WDM-KS (0 in, 2 out)
  16 Headphones 2 (Realtek HD Audio 2nd output with HAP), Windows WDM-KS (0 in, 2 out)
  17 PC Speaker (Realtek HD Audio 2nd output with HAP), Windows WDM-KS (2 in, 0 out)
  18 Headphones (), Windows WDM-KS (0 in, 2 out)
  19 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(P9)), Windows WDM-KS (0 in, 1 out)
  20 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(P9)), Windows WDM-KS (1 in, 0 out)
  21 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Alpha)), Windows WDM-KS (0 in, 1 out)
  22 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Alpha)), Windows WDM-KS (1 in, 0 out)
  23 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Anmol’s AirPods Pro)), Windows WDM-KS (0 in, 1 out)
  24 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Anmol’s AirPods Pro)), Windows WDM-KS (1 in, 0 out)
  25 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Hammer Airflow Plus)), Windows WDM-KS (0 in, 1 out)
  26 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Hammer Airflow Plus)), Windows WDM-KS (1 in, 0 out)
  27 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Boult Audio Airbass)), Windows WDM-KS (0 in, 1 out)
  28 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Boult Audio Airbass)), Windows WDM-KS (1 in, 0 out)
  29 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Rockerz 480)), Windows WDM-KS (0 in, 1 out)
  30 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Rockerz 480)), Windows WDM-KS (1 in, 0 out)
  31 Headphones (), Windows WDM-KS (0 in, 2 out)
  32 Headphones (), Windows WDM-KS (0 in, 2 out)
  33 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes 131)), Windows WDM-KS (0 in, 1 out)
  34 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes 131)), Windows WDM-KS (1 in, 0 out)
  35 Headphones (), Windows WDM-KS (0 in, 2 out)
  36 Headphones (), Windows WDM-KS (0 in, 2 out)
  37 Headphones (), Windows WDM-KS (0 in, 2 out)
  38 Microphone Array (AMDAfdInstall Wave Microphone - 0), Windows WDM-KS (2 in, 0 out)
  39 Headphones (), Windows WDM-KS (0 in, 2 out)
  40 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Redmi Buds 5C)), Windows WDM-KS (0 in, 1 out)
  41 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Redmi Buds 5C)), Windows WDM-KS (1 in, 0 out)
  42 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Unity ANC)), Windows WDM-KS (0 in, 1 out)
  43 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Unity ANC)), Windows WDM-KS (1 in, 0 out)
  44 Headphones (), Windows WDM-KS (0 in, 2 out)
  45 Headphones (), Windows WDM-KS (0 in, 2 out)

In [7]:
import sounddevice as sd
from scipy.io.wavfile import write

fs = 44100
seconds = 5

print("Recording...")

audio = sd.rec(
    int(seconds * fs),
    samplerate=fs,
    channels=1
)

sd.wait()

write(
    "test.wav",
    fs,
    audio
)

print("Saved!")

Recording...
Saved!

In [8]:
from IPython.display import Audio

Audio(
    "test.wav"
)

In [9]:
print(sd.query_devices())

   0 Microsoft Sound Mapper - Input, MME (2 in, 0 out)
>  1 Microphone Array (AMD Audio Dev, MME (2 in, 0 out)
   2 Microsoft Sound Mapper - Output, MME (0 in, 2 out)
<  3 Speakers (Realtek(R) Audio), MME (0 in, 2 out)
   4 Primary Sound Capture Driver, Windows DirectSound (2 in, 0 out)
   5 Microphone Array (AMD Audio Device), Windows DirectSound (2 in, 0 out)
   6 Primary Sound Driver, Windows DirectSound (0 in, 2 out)
   7 Speakers (Realtek(R) Audio), Windows DirectSound (0 in, 2 out)
   8 Speakers (Realtek(R) Audio), Windows WASAPI (0 in, 2 out)
   9 Microphone Array (AMD Audio Device), Windows WASAPI (2 in, 0 out)
  10 Speakers 1 (Realtek HD Audio output with HAP), Windows WDM-KS (0 in, 2 out)
  11 Speakers 2 (Realtek HD Audio output with HAP), Windows WDM-KS (0 in, 2 out)
  12 PC Speaker (Realtek HD Audio output with HAP), Windows WDM-KS (2 in, 0 out)
  13 Stereo Mix (Realtek HD Audio Stereo input), Windows WDM-KS (2 in, 0 out)
  14 Microphone (Realtek HD Audio Mic input), Windows WDM-KS (2 in, 0 out)
  15 Headphones 1 (Realtek HD Audio 2nd output with HAP), Windows WDM-KS (0 in, 2 out)
  16 Headphones 2 (Realtek HD Audio 2nd output with HAP), Windows WDM-KS (0 in, 2 out)
  17 PC Speaker (Realtek HD Audio 2nd output with HAP), Windows WDM-KS (2 in, 0 out)
  18 Headphones (), Windows WDM-KS (0 in, 2 out)
  19 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(P9)), Windows WDM-KS (0 in, 1 out)
  20 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(P9)), Windows WDM-KS (1 in, 0 out)
  21 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Alpha)), Windows WDM-KS (0 in, 1 out)
  22 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Alpha)), Windows WDM-KS (1 in, 0 out)
  23 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Anmol’s AirPods Pro)), Windows WDM-KS (0 in, 1 out)
  24 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Anmol’s AirPods Pro)), Windows WDM-KS (1 in, 0 out)
  25 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Hammer Airflow Plus)), Windows WDM-KS (0 in, 1 out)
  26 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Hammer Airflow Plus)), Windows WDM-KS (1 in, 0 out)
  27 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Boult Audio Airbass)), Windows WDM-KS (0 in, 1 out)
  28 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Boult Audio Airbass)), Windows WDM-KS (1 in, 0 out)
  29 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Rockerz 480)), Windows WDM-KS (0 in, 1 out)
  30 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Rockerz 480)), Windows WDM-KS (1 in, 0 out)
  31 Headphones (), Windows WDM-KS (0 in, 2 out)
  32 Headphones (), Windows WDM-KS (0 in, 2 out)
  33 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes 131)), Windows WDM-KS (0 in, 1 out)
  34 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes 131)), Windows WDM-KS (1 in, 0 out)
  35 Headphones (), Windows WDM-KS (0 in, 2 out)
  36 Headphones (), Windows WDM-KS (0 in, 2 out)
  37 Headphones (), Windows WDM-KS (0 in, 2 out)
  38 Microphone Array (AMDAfdInstall Wave Microphone - 0), Windows WDM-KS (2 in, 0 out)
  39 Headphones (), Windows WDM-KS (0 in, 2 out)
  40 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Redmi Buds 5C)), Windows WDM-KS (0 in, 1 out)
  41 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Redmi Buds 5C)), Windows WDM-KS (1 in, 0 out)
  42 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Unity ANC)), Windows WDM-KS (0 in, 1 out)
  43 Headset (@System32\drivers\bthhfenum.sys,#2;%1 Hands-Free%0
;(Airdopes Unity ANC)), Windows WDM-KS (1 in, 0 out)
  44 Headphones (), Windows WDM-KS (0 in, 2 out)
  45 Headphones (), Windows WDM-KS (0 in, 2 out)

In [21]:
import sounddevice as sd
from scipy.io.wavfile import write

fs = 44100
seconds = 10

audio = sd.rec(
    int(seconds * fs),
    samplerate=fs,
    channels=1,
    dtype='int16'
)

sd.wait()

write(
    "audio.wav",
    fs,
    audio
)

print("Saved")

Saved

In [22]:
import os

print(
    os.path.exists(
        "audio.wav"
    )
)

True

In [23]:
import os

print(
    os.path.getsize(
        "audio.wav"
    )
)

882044

In [10]:
!pip install shazamio

Requirement already satisfied: shazamio in c:\users\amrit\downloads\anaconda\lib\site-packages (0.8.1)
Requirement already satisfied: aiofiles<24.0.0,>=23.2.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (23.2.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (3.10.5)
Requirement already satisfied: aiohttp-retry<3.0.0,>=2.8.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (2.9.1)
Requirement already satisfied: anyio<5.0.0,>=4.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (4.13.0)
Requirement already satisfied: dataclass-factory<3.0,>=2.16 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (2.16)
Collecting numpy<3.0.0,>=2.2.2 (from shazamio)
  Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.9.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (2.13.4)
Requirement already satisfied: pydub<0.26.0,>=0.25.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (0.25.1)
Requirement already satisfied: shazamio-core==1.1.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from shazamio) (1.1.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (2.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->shazamio) (1.11.0)
Requirement already satisfied: idna>=2.8 in c:\users\amrit\downloads\anaconda\lib\site-packages (from anyio<5.0.0,>=4.3.0->shazamio) (3.7)
Requirement already satisfied: typing_extensions>=4.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from anyio<5.0.0,>=4.3.0->shazamio) (4.15.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic<3.0.0,>=2.9.2->shazamio) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic<3.0.0,>=2.9.2->shazamio) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from pydantic<3.0.0,>=2.9.2->shazamio) (0.4.2)
Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
Successfully installed numpy-2.4.6

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~~mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\amrit\Downloads\anaconda\Lib\site-packages\~.mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.6 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.4.6 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.17.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.6 which is incompatible.
pandas-profiling 3.2.0 requires joblib~=1.1.0, but you have joblib 1.5.2 which is incompatible.
pandas-profiling 3.2.0 requires visions[type_image_path]==0.7.4, but you have visions 0.8.1 which is incompatible.
streamlit 1.37.1 requires rich<14,>=10.14.0, but you have rich 15.0.0 which is incompatible.
ydata-profiling 4.16.1 requires numpy<2.2,>=1.16.0, but you have numpy 2.4.6 which is incompatible.
ydata-profiling 4.16.1 requires scipy<1.16,>=1.4.1, but you have scipy 1.17.1 which is incompatible.

In [11]:
import asyncio
from shazamio import Shazam

C:\Users\amrit\Downloads\anaconda\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

In [12]:
async def detect_song():

    shazam = Shazam()

    result = await shazam.recognize(
        "audio.wav"
    )

    return result

In [14]:
!pip install nest_asyncio

Requirement already satisfied: nest_asyncio in c:\users\amrit\downloads\anaconda\lib\site-packages (1.6.0)

In [15]:
import nest_asyncio
nest_asyncio.apply()

In [24]:
result = await detect_song()

In [25]:
track = result.get("track", None)

if track:
    print("Song:", track["title"])
    print("Artist:", track["subtitle"])
else:
    print("No song detected")

Song: Without Me
Artist: Halsey

In [30]:
import pandas as pd

df = pd.read_csv(
    "zuno_dataset.csv"
)

matches = df[
    df['song']
    .str.contains(
        song_name,
        case=False,
        na=False
    )
]

matches[
[
'song',
'artist',
'genre'
]
].head()

Empty DataFrame
Columns: [song, artist, genre]
Index: []

In [27]:
print(result.keys())

dict_keys(['matches', 'location', 'timestamp', 'timezone', 'track', 'tagid'])

In [28]:
track = result['track']

song_name = track['title']
artist_name = track['subtitle']

print("Song:", song_name)
print("Artist:", artist_name)

Song: Without Me
Artist: Halsey

In [29]:
print(song_name)
print(artist_name)

Without Me
Halsey

In [31]:
df['song'].head(20)

0               i'm yours
1         i won't give up
2        93 million miles
3              bella luna
4       winter wonderland
5          if it kills me
6         absolutely zero
7           sleep all day
8          you and i both
9       who needs shelter
10         no stopping us
11       i'll do anything
12          too much food
13         the boy's gone
14    on love, in sadness
15       curbside prophet
16     tonight, not again
17              you and i
18              everybody
19         keep breathing
Name: song, dtype: object

In [32]:
df[
    df['song']
    .str.contains(
        song_name[:5],
        case=False,
        na=False
    )
]

,song,artist,genre,popularity,lyrics
824,don't leave without taking your silver,george jones,honky-tonk,10,You said I'm taking everything that is mine ri...
962,christmas without you,onerepublic,piano,7,"It's almost midnight, where you lay your head ..."

In [33]:
print(len(matches))

0

In [34]:
!pip install rapidfuzz

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError('exception: access violation writing 0x0000000000000048'))': /simple/rapidfuzz/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError('exception: access violation writing 0x0000000000000048'))': /simple/rapidfuzz/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError('exception: access violation writing 0x0000000000000048'))': /simple/rapidfuzz/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError('exception: access violation writing 0x0000000000000048'))': /simple/rapidfuzz/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', OSError('exception: access violation writing 0x0000000000000048'))': /simple/rapidfuzz/
ERROR: Could not find a version that satisfies the requirement rapidfuzz (from versions: none)
ERROR: No matching distribution found for rapidfuzz

In [35]:
from rapidfuzz import process

all_songs = df['song'].tolist()

best_match = process.extractOne(
    song_name,
    all_songs
)

print(best_match)

ModuleNotFoundError: No module named 'rapidfuzz'

In [ ]:
matched_song = best_match[0]

matches = df[
    df['song']
    ==
    matched_song
]

matches[
[
'song',
'artist',
'genre'
]
]

In [36]:
!pip install lyricsgenius

Collecting lyricsgenius
  Downloading lyricsgenius-3.12.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: beautifulsoup4>=4.12.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from lyricsgenius) (4.12.3)
Requirement already satisfied: requests>=2.27.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from lyricsgenius) (2.34.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from beautifulsoup4>=4.12.3->lyricsgenius) (2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests>=2.27.1->lyricsgenius) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests>=2.27.1->lyricsgenius) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests>=2.27.1->lyricsgenius) (2.2.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests>=2.27.1->lyricsgenius) (2024.8.30)
Downloading lyricsgenius-3.12.2-py3-none-any.whl (50 kB)
Installing collected packages: lyricsgenius
Successfully installed lyricsgenius-3.12.2

In [37]:
import lyricsgenius

GENIUS_TOKEN = "Vz_FkNG1JKqMbHKqYrsSjQ8VaHv8KjVIg_hTxMYczw9kXs7tA0QELBSm3WCOw4bL"

genius = lyricsgenius.Genius(
    GENIUS_TOKEN,
    skip_non_songs=True,
    excluded_terms=["(Remix)", "(Live)"]
)

In [38]:
print(song_name)
print(artist_name)

Without Me
Halsey

In [39]:
song = genius.search_song(
    song_name,
    artist_name
)

In [40]:
lyrics = song.lyrics

print(
    lyrics[:3000]
)

[Verse 1]
Found you when your heart was broke
I filled your cup until it overflowed
Took it so far to keep you close (Keep you close)
I was afraid to leave you on your own (Ooh)

[Pre-Chorus]
I said I'd catch you if you fall (Fall)
And if they laugh, then fuck 'em all (All)
And then I got you off your knees
Put you right back on your feet
Just so you could take advantage of me

[Chorus]
Tell me, how's it feel sittin' up there?
Feelin' so high, but too far away to hold me
You know I'm the one who put you up there
Name in the sky, does it ever get lonely?
Thinkin' you could live without me
Thinkin' you could live without me
Baby, I'm the one who put you up there
I don't know why (Yeah, I don't know why)
Thinkin' you could live without me
Live without me
Baby, I'm the one who put you up there
I don't know why (I don't know why, yeah, yeah)

[Verse 2]
Gave love 'bout a hundred tries (Hundred tries)
Just runnin' from the demons in your mind
Then I took yours and made 'em mine (Mine)
I didn't notice 'cause my love was blind

[Pre-Chorus]
Said I'd catch you if you fall (Fall)
And if they laugh, then fuck 'em all (All)
And then I got you off your knees
Put you right back on your feet
Just so you could take advantage of me

[Chorus]
Tell me, how's it feel sittin' up there?
Feelin' so high, but too far away to hold me
You know I'm the one who put you up there
Name in the sky, does it ever get lonely?
Thinkin' you could live without me
Thinkin' you could live without me
Baby, I'm the one who put you up there
I don't know why (Yeah, I don't know why)
Thinkin' you could live without me
Live without me
Baby, I'm the one who put you up there
I don't know why, yeah

[Bridge]
You don't have to say just what you did (What you did)
I already know (I know)
I had to go and find out from them (Oh-woah)
So tell me, how's it feel? (Oh-woah)

[Chorus]
Tell me, how's it feel sittin' up there?
Feelin' so high, but too far away to hold me
You know I'm the one who put you up there
Name in the sky, does it ever get lonely?
Thinkin' you could live without me
Thinkin' you could live without me
Baby, I'm the one who put you up there
I don't know why (Yeah, I don't know why)

In [41]:
with open(
    "live_lyrics.txt",
    "w",
    encoding="utf-8"
) as f:

    f.write(
        lyrics
    )

In [42]:
!pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from deep-translator) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from deep-translator) (2.34.2)
Requirement already satisfied: soupsieve>1.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.2.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\amrit\downloads\anaconda\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2024.8.30)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4

In [43]:
from deep_translator import GoogleTranslator

def translate_lyrics(text):

    text = text[:3000]

    translated = GoogleTranslator(
        source='auto',
        target='en'
    ).translate(text)

    return translated

In [44]:
translated = translate_lyrics(
    lyrics
)

print(
    translated
)

[Verse 1]
Found you when your heart was broke
I filled your cup until it overflowed
Took it so far to keep you close (Keep you close)
I was afraid to leave you on your own (Ooh)

[Pre-Chorus]
I said I'd catch you if you fall (Fall)
And if they laugh, then fuck 'em all (All)
And then I got you off your knees
Put you right back on your feet
Just so you could take advantage of me

[Chorus]
Tell me, how's it feel sittin' up there?
Feelin' so high, but too far away to hold me
You know I'm the one who put you up there
Name in the sky, does it ever get lonely?
Thinkin' you could live without me
Thinkin' you could live without me
Baby, I'm the one who put you up there
I don't know why (Yeah, I don't know why)
Thinkin' you could live without me
Live without me
Baby, I'm the one who put you up there
I don't know why (I don't know why, yeah, yeah)

[Verse 2]
Gave love 'bout a hundred tries (Hundred tries)
Just runnin' from the demons in your mind
Then I took yours and made 'em mine (Mine)
I didn't notice 'cause my love was blind

[Pre-Chorus]
Said I'd catch you if you fall (Fall)
And if they laugh, then fuck 'em all (All)
And then I got you off your knees
Put you right back on your feet
Just so you could take advantage of me

[Chorus]
Tell me, how's it feel sittin' up there?
Feelin' so high, but too far away to hold me
You know I'm the one who put you up there
Name in the sky, does it ever get lonely?
Thinkin' you could live without me
Thinkin' you could live without me
Baby, I'm the one who put you up there
I don't know why (Yeah, I don't know why)
Thinkin' you could live without me
Live without me
Baby, I'm the one who put you up there
I don't know why, yeah

[Bridge]
You don't have to say just what you did (What you did)
I already know (I know)
I had to go and find out from them (Oh-woah)
So tell me, how's it feel? (Oh-woah)

[Chorus]
Tell me, how's it feel sittin' up there?
Feelin' so high, but too far away to hold me
You know I'm the one who put you up there
Name in the sky, does it ever get lonely?
Thinkin' you could live without me
Thinkin' you could live without me
Baby, I'm the one who put you up there
I don't know why (Yeah, I don't know why)

In [45]:
with open(
    "translated_lyrics.txt",
    "w",
    encoding="utf-8"
) as f:

    f.write(
        translated
    )

In [46]:
!pip install transformers torch

Requirement already satisfied: transformers in c:\users\amrit\downloads\anaconda\lib\site-packages (5.10.2)
Requirement already satisfied: torch in c:\users\amrit\downloads\anaconda\lib\site-packages (2.12.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (1.18.0)
Requirement already satisfied: numpy>=1.17 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (2.4.6)
Requirement already satisfied: packaging>=20.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (6.0.1)
Requirement already satisfied: regex>=2025.10.22 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\amrit\downloads\anaconda\lib\site-packages (from transformers) (4.66.5)
Requirement already satisfied: filelock in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (75.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\amrit\downloads\anaconda\lib\site-packages (from torch) (2024.6.1)
Requirement already satisfied: click>=8.4.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\amrit\downloads\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.27.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\users\amrit\downloads\anaconda\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\amrit\downloads\anaconda\lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: anyio in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.2)
Requirement already satisfied: idna in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: sniffio in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\amrit\downloads\anaconda\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.14.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\amrit\downloads\anaconda\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\amrit\downloads\anaconda\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.0)

In [47]:
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis"
)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

C:\Users\amrit\Downloads\anaconda\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\amrit\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [49]:
result = sentiment_model(
    translated[:512]
)

print(result)

[{'label': 'POSITIVE', 'score': 0.995327353477478}]

In [50]:
if result[0]['label'] == "POSITIVE":

    mood = "Happy"

else:

    mood = "Melancholic"

print(
    "Mood:",
    mood
)

Mood: Happy

In [51]:
music_twin = f"""

🎵 Your Music Personality

Current Song:
{song_name}

Artist:
{artist_name}

Mood:
{mood}

This suggests that your
current listening pattern
leans toward emotionally
engaging and immersive music.

"""

print(
    music_twin
)

🎵 Your Music Personality

Current Song:
Without Me

Artist:
Halsey

Mood:
Happy

This suggests that your
current listening pattern
leans toward emotionally
engaging and immersive music.

In [52]:
from datetime import datetime
import pandas as pd

In [60]:
history_entry = {

    "song": song_name,

    "artist": artist_name,

    "timestamp": str(
        datetime.now()
    ),

    "language": language,

    "lyrics": lyrics,

    "translated_lyrics": translated,

    "mood": mood
}

NameError: name 'language' is not defined

In [54]:
entry_df = pd.DataFrame(
    [history_entry]
)

entry_df

,song,artist,timestamp,lyrics,translated_lyrics,mood
0,Without Me,Halsey,2026-06-10 21:27:14.992276,[Verse 1]\nFound you when your heart was broke...,[Verse 1]\nFound you when your heart was broke...,Happy

In [55]:
import os

In [56]:
history_file = "history.csv"

if os.path.exists(
    history_file
):

    old_history = pd.read_csv(
        history_file
    )

    updated_history = pd.concat(
        [
            old_history,
            entry_df
        ],
        ignore_index=True
    )

else:

    updated_history = entry_df

In [58]:
updated_history.to_csv(
    history_file,
    index=False
)

print(
    "History Updated"
)

History Updated

In [59]:
history = pd.read_csv(
    "history.csv"
)

history.tail()

,song,artist,timestamp,lyrics,translated_lyrics,mood
0,Without Me,Halsey,2026-06-10 21:27:14.992276,[Verse 1]\nFound you when your heart was broke...,[Verse 1]\nFound you when your heart was broke...,Happy